# BUSINESS SCIENCE UNIVERSITY
# PYTHON FOR GENERATIVE AI COURSE
# RETRIEVAL-AUGMENTED GENERATION (RAG)
# ***

# CHALLENGE 2: CREATE AN EXPERT IN CANNONDALE BICYCLES BIKE MODELS. GOAL IS TO USE THE LLM TO HELP RECOMMEND BICYCLES TO USERS.

# WEBSITE: https://www.cannondale.com/en-us

# DIFFICULTY: INTERMEDIATE/ADVANCED

# SPECIFIC ACTIONS:
#  1. LOAD WEBPAGES AND STORE THE TEXT WITH METADATA
#  2. CREATE A VECTOR DATABASE TO STORE KNOWLEDGE 
#  3. CREATE A WEB APP THAT INCORPORATES Q&A AND CHAT MEMORY
#  4. BONUS: RETURN IMAGES FOR THE PRODUCTS MENTIONED
